version: '3'
services:
  webapp:
    image: aolifu/meetspot:v1
    container_name: meetspot
    network_mode: "host"
    environment:
      # 或者直接引用宿主机变量：
      - api_key # 会引用宿主机当前的 api_key
    volumes:
      - /root/meetspot/logs:/root/meetspot/logs
